#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 12 13:57:17 2019

@author: kaitlin
"""

def area_circle(radius):
    pi = 3.14159
    area = pi * radius**2
    return area

a = area_circle(1)
print(a)
print('A circle with radius 2 had area {:.2f}'.format(area_circle(2)))
r = 75.1
a = area_circle(r)
print("A circle with radius {:.2f} has area {:.2f}".format(r,a))

"""
local and global areas. variable a is a global variable because it is without
the main scope of the function. use exact name provided in lecture exercise
"""

#write a function to convert mph to kpday

def mph2kpd(mph):
    kph = mph*(8/5)
    kpd = kph*24
    return kpd

print(mph2kpd(0))
print(mph2kpd(1))
print(mph2kpd(1/24))
print(mph2kpd(60))

#do not want to do comparrisons with floating point numbers 

'''
This is a program to calculate the surface area and
volume of a cylinder given a radius and a height.

Radius and height are in float and are user inputs.

Sample Execution:
Enter radius (float) => 12
 Enter height (float) => 10
Surface area is: 1658.76
Volume is: 4523.89

CS1
Wesley Turner
9/18/2017
'''
import math

def area_circle(radius):
    '''
    This function returns the area of a circle with a given radius.
    w
    radius is the input parameter
    '''
    area = math.pi * radius ** 2
    return area

def area_cylinder(h, r):
    '''
    Give a height h and radius r, return the surface area of a cylinder.
    '''
    cap_area = 2 * area_circle(r)
    rect_area = math.pi * 2 * r * h
    return cap_area + rect_area

if __name__ == "__main__":
    r = float(input("Enter radius (float) => "))
    h = float(input("Enter height (float) => "))
    print("Surface area is: {:.2f}".format(area_cylinder(h, r)))
    print("Volume is: {:.2f}".format(h * area_circle(r)))

#if you miss the return value on a function and print the return value it will
    #print out the value of none. this has a type of NoneType which can 
#be assigned to a variable and when you print the value of the variable, the 
#value is none